/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiNewsletterRouteImport } from './routes/api/newsletter'
import { Route as StorySlugRouteImport } from './routes/story.$slug'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminChaptersRouteImport } from './routes/_authenticated/admin/chapters'
import { Route as AuthenticatedAdminContactsRouteImport } from './routes/_authenticated/admin/contacts'
import { Route as AuthenticatedAdminGenresRouteImport } from './routes/_authenticated/admin/genres'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin/newsletter'
import { Route as AuthenticatedAdminStoriesRouteImport } from './routes/_authenticated/admin/stories'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as StorySlugChapterChapterNumberRouteImport } from './routes/story.$slug.chapter.$chapterNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: '/story/$slug',
  path: '/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChaptersRoute =
  AuthenticatedAdminChaptersRouteImport.update({
    id: '/chapters',
    path: '/chapters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactsRoute =
  AuthenticatedAdminContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGenresRoute =
  AuthenticatedAdminGenresRouteImport.update({
    id: '/genres',
    path: '/genres',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStoriesRoute =
  AuthenticatedAdminStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const StorySlugChapterChapterNumberRoute =
  StorySlugChapterChapterNumberRouteImport.update({
    id: '/chapter/$chapterNumber',
    path: '/chapter/$chapterNumber',
    getParentRoute: () => StorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/genres': typeof GenresRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/story/$slug': typeof StorySlugRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/genres': typeof AuthenticatedAdminGenresRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/story/$slug/chapter/$chapterNumber': typeof StorySlugChapterChapterNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/genres': typeof GenresRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/story/$slug': typeof StorySlugRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/genres': typeof AuthenticatedAdminGenresRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/story/$slug/chapter/$chapterNumber': typeof StorySlugChapterChapterNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/audio': typeof AudioRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/genres': typeof GenresRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/story/$slug': typeof StorySlugRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/chapters': typeof AuthenticatedAdminChaptersRoute
  '/_authenticated/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/_authenticated/admin/genres': typeof AuthenticatedAdminGenresRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/story/$slug/chapter/$chapterNumber': typeof StorySlugChapterChapterNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audio'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/genres'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/signup'
    | '/stories'
    | '/terms'
    | '/watch'
    | '/account'
    | '/admin'
    | '/api/contact'
    | '/api/newsletter'
    | '/story/$slug'
    | '/admin/analytics'
    | '/admin/chapters'
    | '/admin/contacts'
    | '/admin/genres'
    | '/admin/newsletter'
    | '/admin/stories'
    | '/admin/users'
    | '/story/$slug/chapter/$chapterNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audio'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/genres'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/signup'
    | '/stories'
    | '/terms'
    | '/watch'
    | '/account'
    | '/admin'
    | '/api/contact'
    | '/api/newsletter'
    | '/story/$slug'
    | '/admin/analytics'
    | '/admin/chapters'
    | '/admin/contacts'
    | '/admin/genres'
    | '/admin/newsletter'
    | '/admin/stories'
    | '/admin/users'
    | '/story/$slug/chapter/$chapterNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/audio'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/genres'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/signup'
    | '/stories'
    | '/terms'
    | '/watch'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/api/contact'
    | '/api/newsletter'
    | '/story/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/chapters'
    | '/_authenticated/admin/contacts'
    | '/_authenticated/admin/genres'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/stories'
    | '/_authenticated/admin/users'
    | '/story/$slug/chapter/$chapterNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AudioRoute: typeof AudioRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CopyrightRoute: typeof CopyrightRoute
  GenresRoute: typeof GenresRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRoute
  TermsRoute: typeof TermsRoute
  WatchRoute: typeof WatchRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  StorySlugRoute: typeof StorySlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$slug': {
      id: '/story/$slug'
      path: '/story/$slug'
      fullPath: '/story/$slug'
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chapters': {
      id: '/_authenticated/admin/chapters'
      path: '/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AuthenticatedAdminChaptersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contacts': {
      id: '/_authenticated/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AuthenticatedAdminContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/genres': {
      id: '/_authenticated/admin/genres'
      path: '/genres'
      fullPath: '/admin/genres'
      preLoaderRoute: typeof AuthenticatedAdminGenresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stories': {
      id: '/_authenticated/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AuthenticatedAdminStoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/story/$slug/chapter/$chapterNumber': {
      id: '/story/$slug/chapter/$chapterNumber'
      path: '/chapter/$chapterNumber'
      fullPath: '/story/$slug/chapter/$chapterNumber'
      preLoaderRoute: typeof StorySlugChapterChapterNumberRouteImport
      parentRoute: typeof StorySlugRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminChaptersRoute: typeof AuthenticatedAdminChaptersRoute
  AuthenticatedAdminContactsRoute: typeof AuthenticatedAdminContactsRoute
  AuthenticatedAdminGenresRoute: typeof AuthenticatedAdminGenresRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminStoriesRoute: typeof AuthenticatedAdminStoriesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminChaptersRoute: AuthenticatedAdminChaptersRoute,
  AuthenticatedAdminContactsRoute: AuthenticatedAdminContactsRoute,
  AuthenticatedAdminGenresRoute: AuthenticatedAdminGenresRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminStoriesRoute: AuthenticatedAdminStoriesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StorySlugRouteChildren {
  StorySlugChapterChapterNumberRoute: typeof StorySlugChapterChapterNumberRoute
}

const StorySlugRouteChildren: StorySlugRouteChildren = {
  StorySlugChapterChapterNumberRoute: StorySlugChapterChapterNumberRoute,
}

const StorySlugRouteWithChildren = StorySlugRoute._addFileChildren(
  StorySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AudioRoute: AudioRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CopyrightRoute: CopyrightRoute,
  GenresRoute: GenresRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRoute,
  TermsRoute: TermsRoute,
  WatchRoute: WatchRoute,
  ApiContactRoute: ApiContactRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  StorySlugRoute: StorySlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
